FROM dart 
#используется как основа для сборки контейнера
LABEL version="1.0"
# версия надо

WORKDIR /pr3/dart
# рабочая дериктория

COPY calc.dart /pr3/dart/
# копирование рабочих файлов

CMD [ "dart", "calc.dart" ]
# запуск необходимого файла