FROM nginx:alpine
#используется как основа для сборки контейнера

COPY index.html ./usr/share/nginx/html
#опирует файл index.html из текущей директории внутрь контейнера 
#в директорию /usr/share/nginx/html. 
EXPOSE 80
#объявляет порт 80 для http запросов

