FROM openjdk:17 
# библиотека для java
LABEL version="1.0"
# версия 

WORKDIR /pr3/java
# рабочая дериктория

COPY calc.java /pr3/java/
# копирование рабочих файлов

CMD [ "java", "calc.java" ]
# запуск необходимого файла