FROM python:alpine
#используется как основа для сборки контейнера
LABEL version="1.0"
# версия надо

WORKDIR /pr3/game-python
# рабочая дериктория 

COPY RockPaperScissorsGame.py /pr3/game-python/
# копирование рабочих файлов

CMD [ "python", "RockPaperScissorsGame.py" ]
# запуск необходимого файла